name: Run custom action
on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "Johny"
      - name: Display Time of greeting
        if: always()
        run: |
          echo "Time of greeting: ${{ steps.hello.outputs.time }}"
          # Variable set with core package in previous step
          echo "HELLO=${HELLO}"
      - name: Create Issue
        uses: ./.github/actions/issue
        id: issue
        with:
          token: "${{ github.GITHUB_TOKEN }}"
          title: "Title of issue"
          body: "Body of an issue"
          assignees: "radoscis,piotrjanis"
      - name: Get output
        run: |
          echo "Issue: "
          echo ${{ steps.issue.outputs.issue }}