name: Run custom action
on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "Johny"
      - name: Display Time of greeting
        if: failure()
        run: |
          echo "Time of greeting: ${{ steps.hello.outputs.time }}"
      - uses: ./.github/actions/hello-docker
        if: always()
        id: helloDocker
        with:
          who-to-greet: "Johny"
      - name: Display Time of greeting form docker and env var
        if: always()
        run: |
          echo "Time of greeting: ${{ steps.helloDocker.outputs.time }}"
          echo "Hello Value: ${{ env.HELLO }}"
      - name: Add collaborator
        uses: ./.github/actions/add-collaborator
        if: always()
        id: addCollaborator
        with:
          repo: ${{ env.GITHUB_REPOSITORY }}
          collaborator: piotrjanis
          token: ${{ secrets.GH_TOKEN }}
