name: Test Add Collaborator Action
on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - name: Add collaborator
        uses: ./.github/actions/add-collaborator
        if: always()
        id: addCollaborator
        with:
          repo: ${{ env.GITHUB_REPOSITORY }}
          collaborator: piotrjanis
          token: ${{ secrets.GH_TOKEN }}
